"""Report generation for ValueGuard."""

import json
from datetime import datetime
from typing import Any, Optional

from valueguard.core.config import Config
from valueguard.core.models import ValueGuardReport


class Reporter:
    """Generate reports from ValueGuard analysis results.

    Supports multiple output formats:
    - JSON
    - Markdown (for PR comments)
    - Console (for CLI output)
    """

    def __init__(self, config: Optional[Config] = None):
        """Initialize reporter.

        Args:
            config: ValueGuard configuration
        """
        self.config = config

    def to_json(self, report: ValueGuardReport) -> str:
        """Generate JSON report.

        Args:
            report: Analysis report

        Returns:
            JSON string
        """
        data = self._report_to_dict(report)
        return json.dumps(data, indent=2, default=str)

    def to_markdown(self, report: ValueGuardReport) -> str:
        """Generate Markdown report for PR comment.

        Args:
            report: Analysis report

        Returns:
            Markdown string
        """
        lines = []

        # Header with risk badge
        risk_badge = self._get_risk_badge(report.overall_risk_score)
        lines.append(f"## ValueGuard Analysis {risk_badge}")
        lines.append("")

        # Summary
        lines.append("### Summary")
        lines.append("")
        lines.append(f"- **Overall Risk Score**: {report.overall_risk_score:.2f}")
        lines.append(f"- **Hypotheses Generated**: {len(report.hypotheses)}")
        confirmed = sum(1 for e in report.evidences if e.is_confirmed)
        lines.append(f"- **Confirmed Findings**: {confirmed}")
        lines.append("")

        # Value scores (if any)
        if report.value_scores:
            lines.append("### Value Risk Scores")
            lines.append("")
            lines.append("| Value | Score | Severity | Findings |")
            lines.append("|-------|-------|----------|----------|")
            for score in report.value_scores[:5]:  # Top 5
                lines.append(
                    f"| {score.value_id} ({score.value_name}) | "
                    f"{score.score:.2f} | {score.severity} | "
                    f"{score.evidence_count}/{score.hypothesis_count} |"
                )
            lines.append("")

        # Top findings
        top_findings = report.get_top_risks(5)
        if top_findings:
            lines.append("### Top Findings")
            lines.append("")

            evidence_map = {e.hypothesis_id: e for e in report.evidences}

            for i, h in enumerate(top_findings, 1):
                severity_emoji = {
                    "critical": "🔴",
                    "high": "🟠",
                    "medium": "🟡",
                    "low": "🟢",
                }.get(h.severity, "⚪")

                lines.append(f"#### {i}. {h.value_id} - {h.deviation_type.title()} {severity_emoji}")
                lines.append("")
                lines.append(f"**Confidence**: {h.confidence:.2f} | **Severity**: {h.severity}")
                lines.append("")
                lines.append(f"> {h.description}")
                lines.append("")

                # Add evidence location
                evidence = evidence_map.get(h.id)
                if evidence and evidence.evidence_pieces:
                    piece = evidence.evidence_pieces[0]
                    lines.append(f"📍 **Location**: `{piece.file_path}:{piece.start_line}`")
                    lines.append("")
                    if piece.snippet:
                        lines.append("```")
                        lines.append(piece.snippet[:500])
                        lines.append("```")
                        lines.append("")

                if h.suggested_action:
                    lines.append(f"💡 **Suggestion**: {h.suggested_action}")
                    lines.append("")

        # Cross-layer trace (if available)
        if top_findings and any(h.cross_layer_trace for h in top_findings):
            lines.append("### Value Reasoning Trace")
            lines.append("")
            for h in top_findings:
                if h.cross_layer_trace:
                    trace = h.cross_layer_trace
                    lines.append(f"**{h.value_id}**: {trace.l1_value} → {trace.l2_theme} → {trace.l3_attribute} → {trace.l4_indicator}")
                    if trace.reasoning:
                        lines.append(f"  - _{trace.reasoning}_")
            lines.append("")

        # Mentions
        if report.mentions:
            lines.append("### Reviewers")
            lines.append("")
            lines.append(f"cc: {' '.join(report.mentions)}")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append(f"_Generated by ValueGuard at {report.timestamp.strftime('%Y-%m-%d %H:%M:%S')}_")

        return "\n".join(lines)

    def to_console(self, report: ValueGuardReport) -> str:
        """Generate console-friendly report.

        Args:
            report: Analysis report

        Returns:
            Console output string
        """
        lines = []

        # Header
        lines.append("=" * 60)
        lines.append("VALUEGUARD ANALYSIS REPORT")
        lines.append("=" * 60)
        lines.append("")

        # Summary
        lines.append(f"Repository: {report.repo}")
        lines.append(f"Timestamp: {report.timestamp}")
        lines.append(f"Event: {report.event_type}")
        if report.pr_number:
            lines.append(f"PR: #{report.pr_number}")
        lines.append("")

        # Risk score
        risk_level = self._get_risk_level(report.overall_risk_score)
        lines.append(f"Overall Risk: {report.overall_risk_score:.2f} ({risk_level})")
        lines.append("")

        # Value scores
        if report.value_scores:
            lines.append("-" * 40)
            lines.append("VALUE RISK SCORES")
            lines.append("-" * 40)
            for score in report.value_scores[:5]:
                bar = self._get_bar(score.score)
                lines.append(
                    f"  {score.value_id:12} {bar} {score.score:.2f} "
                    f"[{score.severity}] ({score.evidence_count}/{score.hypothesis_count})"
                )
            lines.append("")

        # Top findings
        top_findings = report.get_top_risks(3)
        if top_findings:
            lines.append("-" * 40)
            lines.append("TOP FINDINGS")
            lines.append("-" * 40)
            evidence_map = {e.hypothesis_id: e for e in report.evidences}

            for i, h in enumerate(top_findings, 1):
                lines.append(f"  [{i}] {h.value_id} - {h.deviation_type}")
                lines.append(f"      Confidence: {h.confidence:.2f} | Severity: {h.severity}")
                lines.append(f"      {h.description[:80]}...")

                evidence = evidence_map.get(h.id)
                if evidence and evidence.evidence_pieces:
                    piece = evidence.evidence_pieces[0]
                    lines.append(f"      Location: {piece.file_path}:{piece.start_line}")
                lines.append("")

        lines.append("=" * 60)
        return "\n".join(lines)

    def _report_to_dict(self, report: ValueGuardReport) -> dict[str, Any]:
        """Convert report to dictionary for JSON serialization."""
        return {
            "repo": report.repo,
            "timestamp": report.timestamp.isoformat(),
            "event_type": report.event_type,
            "pr_number": report.pr_number,
            "commit_sha": report.commit_sha,
            "overall_risk_score": report.overall_risk_score,
            "value_scores": [
                {
                    "value_id": s.value_id,
                    "value_name": s.value_name,
                    "score": s.score,
                    "severity": s.severity,
                    "hypothesis_count": s.hypothesis_count,
                    "evidence_count": s.evidence_count,
                }
                for s in report.value_scores
            ],
            "hypotheses": [
                {
                    "id": h.id,
                    "value_id": h.value_id,
                    "deviation_type": h.deviation_type,
                    "confidence": h.confidence,
                    "severity": h.severity,
                    "description": h.description,
                    "suggested_action": h.suggested_action,
                    "cross_layer_trace": {
                        "l1_value": h.cross_layer_trace.l1_value,
                        "l2_theme": h.cross_layer_trace.l2_theme,
                        "l3_attribute": h.cross_layer_trace.l3_attribute,
                        "l4_indicator": h.cross_layer_trace.l4_indicator,
                        "reasoning": h.cross_layer_trace.reasoning,
                    }
                    if h.cross_layer_trace
                    else None,
                }
                for h in report.hypotheses
            ],
            "evidences": [
                {
                    "hypothesis_id": e.hypothesis_id,
                    "status": e.status.value
                    if hasattr(e.status, "value")
                    else str(e.status),
                    "evidence_pieces": [
                        {
                            "file_path": p.file_path,
                            "start_line": p.start_line,
                            "end_line": p.end_line,
                            "snippet": p.snippet[:200],
                            "relevance_score": p.relevance_score,
                        }
                        for p in e.evidence_pieces
                    ],
                }
                for e in report.evidences
            ],
            "mentions": report.mentions,
        }

    def _get_risk_badge(self, score: float) -> str:
        """Get risk badge for markdown."""
        if score >= 0.8:
            return "🔴 **CRITICAL**"
        elif score >= 0.6:
            return "🟠 **HIGH**"
        elif score >= 0.4:
            return "🟡 **MEDIUM**"
        elif score >= 0.2:
            return "🟢 **LOW**"
        else:
            return "✅ **MINIMAL**"

    def _get_risk_level(self, score: float) -> str:
        """Get risk level string."""
        if score >= 0.8:
            return "CRITICAL"
        elif score >= 0.6:
            return "HIGH"
        elif score >= 0.4:
            return "MEDIUM"
        elif score >= 0.2:
            return "LOW"
        else:
            return "MINIMAL"

    def _get_bar(self, score: float, width: int = 20) -> str:
        """Generate ASCII progress bar."""
        filled = int(score * width)
        empty = width - filled
        return f"[{'█' * filled}{'░' * empty}]"
